[package]
name = "veripb-repl"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.92.0"
repository = ""
description = "An interactive REPL/TUI for exploring and building VeriPB proofs."

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.104"
crossterm = "0.29"
tempfile = "3"

[lib]
name = "veripb_repl"
path = "src/lib.rs"

[[bin]]
name = "veripb-repl"
path = "src/main.rs"
